### ISSUE TITLE
Create a new processor first, by invoking it: use `processor()` instead of `processor`.

### ISSUE THREAD

**Issue by callmeberzerker** [pngwn/MDsveX#718]
I upgraded my blog (svelte-kit 2) that has been working perfectly for 2 years with mdsvex from `mdsvex@^0.12.3` to `^mdsvex@0.12.5` and it yielded the above error.  

My svelte.config.js is as follows:

```js
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte'
import vercelAdapter from '@sveltejs/adapter-vercel'
import mdsvexConfig from './mdsvex.config.js'
import { mdsvex } from 'mdsvex'

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessor

  extensions: ['.svelte', ...mdsvexConfig.extensions],
  preprocess: [
    mdsvex(mdsvexConfig),
    vitePreprocess({
      postcss: true,
    }),
  ],

  kit: {
    adapter: vercelAdapter(),
  },
}

export default config

```

And my mdsvex.config.js is as follows:

```js
import remarkGithub from 'remark-github'
import remarkAbbr from 'remark-abbr'
import rehypeSlug from 'rehype-slug'
import rehypeAutolinkHeadings from 'rehype-autolink-headings'
import rehypeExternalLinks from 'rehype-external-links'

export default {
  extensions: ['.svelte.md', '.md', '.svx'],
  smartypants: {
    dashes: 'oldschool',
  },
  remarkPlugins: [
    [
      remarkGithub,
      {
        repository: 'https://github.com/callmeberzerker/portfolio',
      },
    ],
    remarkAbbr,
  ],
  rehypePlugins: [
    rehypeSlug,
    [
      rehypeAutolinkHeadings,
      {
        behavior: 'wrap',
      },
    ],
    rehypeExternalLinks,
    {
      target: true,
    },
  ],
}

```

**Comment by pngwn** [comment]
Thanks for the report!

Could you share the versions for your dependencies so I can reproduce please?

**Comment by Makosai** [comment]
I actually ran into this issue recently. I fixed another issue with layout paths not resolving. I'll post an issue on that for others later.

But here's what I found on this current issue: https://github.com/Quaint-Studios/playreia/issues/64

https://github.com/Quaint-Studios/playreia/compare/ff056775085dbfc36eb9b20d0a9f9a02ee2338c4..a658a6b7cc0ed5c98e78abc3e4f80c5ef8d328ab

SHA: ff056775085dbfc36eb9b20d0a9f9a02ee2338c4 works. I've even redeployed it several times.
SHA: a658a6b7cc0ed5c98e78abc3e4f80c5ef8d328ab doesn't work. I've tried building it locally and remotely and I get the same issue:

What's even more odd is that if I build *twice* locally, it gives me the error. Checking out main then checking out ff05677 fixes it. I checked out your usage of `unified` as well and it all seems fine at a glance.

**Comment by pngwn** [comment]
Hmm, interesting. 

Yeah, I have pretty extensive tests for the library so I'd be surprised if anything in the core was directly responsible because this is a pretty significant breakage. 

What could be happening is some specific plugin or wrong version being pulled in transitively and is causing some kind of issue . Mdsvex is bundled atm so this shouldn't happen from a technical PoV but I may have missed something. 

Will try to reproduce.

**Comment by lisez** [comment]
I face the same issue too. I downgrade to mdsvex v0.12.4 then fix it.

**Comment by werls** [comment]
The same thing happened to me when I tried to build on Vercel. I tried downgrading, but the issue persists. It's building fine locally.

**Comment by trondhauklien** [comment]
I had the same problem migrating from 0.12.3 to 0.12.5.

```log
error during build:
[vite-plugin-svelte] [plugin vite-plugin-svelte] Error while preprocessing src/routes/+page.svelte.md - Cannot invoke `use` on a frozen processor.
Create a new processor first, by invoking it: use `processor()` instead of `processor`.
```

Following the stack trace lead me to believe it is related to changes made to the `transform()` function in #709:

https://github.com/pngwn/MDsveX/blob/bdf1ca706769113aa647dc39c92dc29706caa974/packages/mdsvex/src/index.ts#L105-L116

**Comment by werls** [comment]
I'm not sure why this is happening, but I'm getting the same error when I try to build the site on Vercel:

````
[16:52:08.385] [36mvite v6.3.5 [32mbuilding SSR bundle for production...[36m[39m
[16:52:08.442] transforming...
[16:52:08.565] [32m✓[39m 8 modules transformed.
[16:52:08.567] [31m✗[39m Build failed in 147ms
[16:52:08.567] [31merror during build:
[16:52:08.567] [31m[vite-plugin-svelte] [plugin vite-plugin-svelte] Error while preprocessing /vercel/path0/src/routes/sobreathos/+page.md - Cannot invoke `use` on a frozen processor.
[16:52:08.567] Create a new processor first, by invoking it: use `processor()` instead of `processor`.[31m
[16:52:08.567] file: [36m/vercel/path0/src/routes/sobreathos/+page.md[31m
[16:52:08.567] Error: [plugin vite-plugin-svelte] Error while preprocessing /vercel/path0/src/routes/sobreathos/+page.md - Cannot invoke `use` on a frozen processor.
[16:52:08.568] Create a new processor first, by invoking it: use `processor()` instead of `processor`.
[16:52:08.568]     at assertUnfrozen$1 (file:///vercel/path0/node_modules/.pnpm/mdsvex@0.12.5_svelte@5.28.2/node_modules/mdsvex/dist/main-CkT3KbbK.js:1167:11)
[16:52:08.568]     at Function.use (file:///vercel/path0/node_modules/.pnpm/mdsvex@0.12.5_svelte@5.28.2/node_modules/mdsvex/dist/main-CkT3KbbK.js:899:5)
[16:52:08.568]     at processor.add_layouts (file:///vercel/path0/node_modules/.pnpm/mdsvex@0.12.5_svelte@5.28.2/node_modules/mdsvex/dist/main-CkT3KbbK.js:24330:13)
[16:52:08.568]     at markup (file:///vercel/path0/node_modules/.pnpm/mdsvex@0.12.5_svelte@5.28.2/node_modules/mdsvex/dist/main-CkT3KbbK.js:24546:12)
[16:52:08.568]     at async process_markup (file:///vercel/path0/node_modules/.pnpm/svelte@5.28.2/node_modules/svelte/src/compiler/preprocess/index.js:309:20)
[16:52:08.568]     at async Module.preprocess (file:///vercel/path0/node_modules/.pnpm/svelte@5.28.2/node_modules/svelte/src/compiler/preprocess/index.js:355:25)
[16:52:08.568]     at async compileSvelte (file:///vercel/path0/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.28.2_vite@6.3.5_jiti@2.4.2_lightningcss@1.29.2_/node_modules/@sveltejs/vite-plugin-svelte/src/utils/compile.js:85:20)
[16:52:08.568]     at async Object.transform (file:///vercel/path0/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@5.0.3_svelte@5.28.2_vite@6.3.5_jiti@2.4.2_lightningcss@1.29.2_/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:164:20)
[16:52:08.570]     at async transform (file:///vercel/path0/node_modules/.pnpm/rollup@4.40.2/node_modules/rollup/dist/es/shared/node-entry.js:20928:16)
[16:52:08.570]     at async ModuleLoader.addModuleSource (file:///vercel/path0/node_modules/.pnpm/rollup@4.40.2/node_modules/rollup/dist/es/shared/node-entry.js:21141:36)[39m
[16:52:08.631]  ELIFECYCLE  Command failed with exit code 1.
[16:52:08.651] Error: Command "pnpm run build" exited with 1
[16:52:08.812] 
```

Locally, the build process works fine. I've noticed that the issue occurs when I have more than one +page.md or +page.svx file, even if they are in different routes.

**Comment by pngwn** [comment]
This should be fixed in 0.12.6 if you could give that a spin!

**Comment by trondhauklien** [comment]
> This should be fixed in 0.12.6 if you could give that a spin!

Thank you. Works like a charm for me.
